### ISSUE TITLE
compile issue 

### ISSUE THREAD

**Issue by RaviRai-Studio** [Devlrxxh/Neptune#15]
dev.lrxh:Build:jar:1.0 was not found in https://mvnrepository.com/artifact/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of mvnrepo has elapsed or updates are forced

Try to run Maven import with -U flag (force update snapshots)

dev.lrxh:Client:jar:1.0-SNAPSHOT was not found in https://mvnrepository.com/artifact/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of mvnrepo has elapsed or updates are forced

Try to run Maven import with -U flag (force update snapshots)

Unresolved dependency: 'dev.lrxh:Build:jar:1.0'
Unresolved dependency: 'dev.lrxh:Client:jar:1.0-SNAPSHOT'

**Comment by Devlrxxh** [comment]
You need to install VersionControll and Loader from my github
