### ISSUE TITLE
Hey, is this link broken? I can't find the dependency.

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [Devlrxxh/Neptune#3]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-codemc-releases.xml [https://repo.codemc.io/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-spigotmc-repo.xml [https://hub.spigotmc.org/nexus/content/repositories/snapshots/]
[WARNING] Could not transfer metadata org.spigotmc:spigot-api:1.16.1-R0.1-SNAPSHOT/maven-metadata.xml from/to spigotmc-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/): status code: 502, reason phrase: Bad Gateway (502)
[WARNING] org.spigotmc:spigot-api:1.16.1-R0.1-SNAPSHOT/maven-metadata.xml failed to transfer from https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of spigotmc-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.spigotmc:spigot-api:1.16.1-R0.1-SNAPSHOT/maven-metadata.xml from/to spigotmc-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/): status code: 502, reason phrase: Bad Gateway (502)
[WARNING] Failed to download maven-metadata-mvnrepo.xml [https://mvnrepository.com/artifact/]
[WARNING] Failed to download maven-metadata-codemc-releases.xml [https://repo.codemc.io/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Could not transfer metadata io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT/maven-metadata.xml from/to mvnrepo (https://mvnrepository.com/artifact/): status code: 403, reason phrase: Forbidden (403)
[WARNING] io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT/maven-metadata.xml failed to transfer from https://mvnrepository.com/artifact/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of mvnrepo has elapsed or updates are forced. Original error: Could not transfer metadata io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT/maven-metadata.xml from/to mvnrepo (https://mvnrepository.com/artifact/): status code: 403, reason phrase: Forbidden (403)
[WARNING] Failed to download maven-metadata-mvnrepo.xml [https://mvnrepository.com/artifact/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download maven-metadata-papermc-repo.xml [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download maven-metadata-codemc-releases.xml [https://repo.codemc.io/repository/maven-releases/]
[WARNING] Could not transfer metadata co.aikar:acf-paper:0.5.1-SNAPSHOT/maven-metadata.xml from/to mvnrepo (https://mvnrepository.com/artifact/): status code: 403, reason phrase: Forbidden (403)
[WARNING] co.aikar:acf-paper:0.5.1-SNAPSHOT/maven-metadata.xml failed to transfer from https://mvnrepository.com/artifact/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of mvnrepo has elapsed or updates are forced. Original error: Could not transfer metadata co.aikar:acf-paper:0.5.1-SNAPSHOT/maven-metadata.xml from/to mvnrepo (https://mvnrepository.com/artifact/): status code: 403, reason phrase: Forbidden (403)
[WARNING] Failed to download maven-metadata-mvnrepo.xml [https://mvnrepository.com/artifact/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download maven-metadata-papermc-repo.xml [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download maven-metadata-codemc-releases.xml [https://repo.codemc.io/repository/maven-releases/]
[WARNING] Could not transfer metadata co.aikar:acf-parent:0.5.1-SNAPSHOT/maven-metadata.xml from/to mvnrepo (https://mvnrepository.com/artifact/): status code: 403, reason phrase: Forbidden (403)
[WARNING] Failed to download Build-1.0.pom [https://mvnrepository.com/artifact/]
[WARNING] Failed to download Build-1.0.pom [https://repo.aikar.co/content/groups/aikar/]
[WARNING] Failed to download Build-1.0.pom [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download Build-1.0.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download Build-1.0.pom [https://repo.codemc.io/repository/maven-releases/]
无法解析 dev.lrxh:Build:1.0

**Comment by Devlrxxh** [comment]
You need to install the [VersionControll](https://github.com/Devlrxxh/VersionControll) from my github
